# Generated by Django 4.2.4 on 2024-06-04 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0003_alter_message_message_mailing_logs'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mailing',
            options={'permissions': [('set_status', 'Can change status of mailing')], 'verbose_name': 'Рассылка', 'verbose_name_plural': 'Рассылки'},
        ),
        migrations.RemoveField(
            model_name='mailing',
            name='period',
        ),
        migrations.AddField(
            model_name='mailing',
            name='periodicity',
            field=models.CharField(choices=[('Единоразово', 'Единоразово'), ('Ежедневно', 'Ежедневно'), ('Еженедельно', 'Еженедельно'), ('Ежемесячно', 'Ежемесячно')], default='Единоразово', max_length=25, verbose_name='Периодичность'),
        ),
    ]
