# Generated by Django 4.2.4 on 2024-06-06 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0004_alter_mailing_options_remove_mailing_period_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mailing',
            name='status',
        ),
        migrations.AddField(
            model_name='mailing',
            name='date_end',
            field=models.DateField(blank=True, null=True, verbose_name='Дата окончания'),
        ),
        migrations.AddField(
            model_name='mailing',
            name='date_start',
            field=models.DateField(blank=True, null=True, verbose_name='Дата начала'),
        ),
        migrations.AlterField(
            model_name='mailing',
            name='periodicity',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Ежедневно'), (7, 'Еженедельно'), (30, 'Ежемесячно')], verbose_name='Периодичность в днях'),
        ),
        migrations.AlterField(
            model_name='mailing',
            name='time',
            field=models.TimeField(verbose_name='Время запуска'),
        ),
    ]
