# Generated by Django 4.2.4 on 2024-06-06 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0005_remove_mailing_status_mailing_date_end_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailing',
            name='date_end',
            field=models.DateField(verbose_name='Дата окончания'),
        ),
        migrations.AlterField(
            model_name='mailing',
            name='date_start',
            field=models.DateField(verbose_name='Дата начала'),
        ),
    ]
