# Generated by Django 4.2.4 on 2024-06-12 13:13

from django.db import migrations, models
import django.utils.datetime_safe


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0006_alter_mailing_date_end_alter_mailing_date_start'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailing',
            name='status',
            field=models.CharField(choices=[('Создана', 'Создана'), ('Запущена', 'Запущена'), ('Завершена', 'Завершена')], default='Создана', max_length=25, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='mailing',
            name='periodicity',
            field=models.CharField(choices=[(1, 'Ежедневно'), (7, 'Еженедельно'), (30, 'Ежемесячно')], default=1, max_length=25, verbose_name='Периодичность'),
        ),
        migrations.AlterField(
            model_name='mailing',
            name='time',
            field=models.DateTimeField(default=django.utils.datetime_safe.datetime.now, verbose_name='Время запуска'),
        ),
    ]
