# Generated by Django 4.2.4 on 2024-06-12 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0007_mailing_status_alter_mailing_periodicity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailing',
            name='periodicity',
            field=models.CharField(choices=[('Ежедневно', 'Ежедневно'), ('Еженедельно', 'Еженедельно'), ('Ежемесячно', 'Ежемесячно')], default='Ежедневно', max_length=25, verbose_name='Периодичность'),
        ),
        migrations.AlterField(
            model_name='mailing',
            name='time',
            field=models.TimeField(verbose_name='Время запуска'),
        ),
    ]
