# Generated by Django 4.2.4 on 2024-06-12 13:25

from django.db import migrations, models
import django.utils.datetime_safe


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0008_alter_mailing_periodicity_alter_mailing_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailing',
            name='time',
            field=models.DateTimeField(default=django.utils.datetime_safe.datetime.now, verbose_name='Время'),
        ),
    ]
