# Generated by Django 4.2.4 on 2024-06-12 15:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0010_alter_mailing_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailing',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 12, 15, 23, 6, 314003, tzinfo=datetime.timezone.utc), verbose_name='Время'),
        ),
    ]
