# Generated by Django 4.2.4 on 2024-06-18 09:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0011_alter_mailing_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailing',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 18, 9, 27, 43, 346320, tzinfo=datetime.timezone.utc), verbose_name='Время'),
        ),
    ]
